# Generated by Django 2.1.5 on 2019-01-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=20, verbose_name='分类名')),
                ('cover', models.ImageField(upload_to='category', verbose_name='分类封面')),
                ('level', models.IntegerField(choices=[(0, '一级分类'), (1, '二级分类'), (2, '三级分类')], verbose_name='分类等级')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'app_category',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('cover', models.ImageField(height_field='height', upload_to='images', verbose_name='图片', width_field='width')),
                ('width', models.IntegerField(verbose_name='宽度')),
                ('height', models.IntegerField(verbose_name='高度')),
            ],
            options={
                'verbose_name': '图片管理',
                'verbose_name_plural': '图片管理',
                'db_table': 'app_cover',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('barcode', models.CharField(max_length=50, verbose_name='条形码')),
                ('cover', models.ImageField(upload_to='goods', verbose_name='封面')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodsapp.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'app_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('info', models.TextField(verbose_name='详情描述')),
                ('covers', models.ManyToManyField(to='goodsapp.Cover')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Goods')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
                'db_table': 'app_goodsdetail',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('total_count', models.IntegerField(default=100, verbose_name='存量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Goods', verbose_name='商品名称')),
            ],
            options={
                'verbose_name': '库存信息',
                'verbose_name_plural': '库存信息',
                'db_table': 'app_storage',
            },
        ),
    ]
