# Generated by Django 2.1.5 on 2019-01-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20190124_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='分类封面'),
        ),
    ]
