# Generated by Django 2.1.5 on 2019-01-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('cover', models.ImageField(upload_to='actives', verbose_name='活动图片')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('active_type', models.IntegerField(choices=[(0, '全场折扣'), (1, '限时折扣')], verbose_name='活动类型')),
                ('discount', models.DecimalField(decimal_places=2, default=0.88, max_digits=4, verbose_name='折扣率')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'db_table': 'app_active',
            },
        ),
    ]
