# Generated by Django 2.1.5 on 2019-01-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20190122_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户头像'),
        ),
    ]
