# Generated by Django 2.1.5 on 2019-01-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('order_count', models.IntegerField(verbose_name='订单数量')),
                ('order_price', models.FloatField(verbose_name='订单总金额')),
                ('order_cancel_count', models.IntegerField(verbose_name='取消订单数量')),
                ('order_candel_price', models.FloatField(verbose_name='取消订单金额')),
            ],
            options={
                'verbose_name': '订单统计',
                'verbose_name_plural': '订单统计',
                'db_table': 'order_record',
            },
        ),
    ]
