# Generated by Django 2.1.5 on 2019-01-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecord',
            old_name='order_candel_price',
            new_name='order_cancel_price',
        ),
    ]
