# Generated by Django 2.1.5 on 2019-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20190122_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
