# Generated by Django 2.1.5 on 2019-01-23 03:21

import base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userprofile_photo'),
        ('orderapp', '0003_auto_20190122_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('info', models.CharField(max_length=100, verbose_name='收货地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserProfile', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 'app_address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('pay_type', models.IntegerField(choices=[(0, '余额'), (1, '支付宝'), (2, '微信')], default=0, verbose_name='支付类型')),
                ('pay_statue', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已评价'), (3, '已退款')], default=0, verbose_name='订单状态')),
                ('order_num', base.OrderNumAutoField(max_length=15, verbose_name='订单号')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderapp.Address', verbose_name='收货信息')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'app_order',
            },
        ),
    ]
